AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for E-Commerce Backend'

Parameters:
  ProjectName:
    Type: String
    Default: ecommerce-backend

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  RepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub '${ProjectName}-ecr-uri'
  RepositoryArn:
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub '${ProjectName}-ecr-arn'