AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Fargate Cluster for E-Commerce Backend'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
    Default: ecommerce-backend

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ProjectName}-${Environment}-cluster'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ClusterCapacityProviders:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      Cluster: !Ref ECSCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
          Base: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 4

Outputs:
  ClusterArn:
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-cluster-arn'
  ClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${ProjectName}-${Environment}-cluster-name'