AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack for E-Commerce Backend - orchestrates all nested stacks'

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, staging, prod]
    Default: dev
  ProjectName:
    Type: String
    Default: ecommerce-backend
  GitHubOwner:
    Type: String
    Description: GitHub repository owner
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: main
  TemplatesBucket:
    Type: String
    Description: S3 bucket containing CloudFormation templates

Resources:
  # VPC and Networking
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/vpc-networking.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Security Groups
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/security-groups.yaml'
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ECR Repository
  ECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/ecr-repository.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Secrets Manager
  SecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/secrets-manager.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # RDS Database
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [VPCStack, SecurityGroupStack, SecretsStack]
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/rds-database.yaml'
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnets: !GetAtt VPCStack.Outputs.PrivateSubnets
        DatabaseSecurityGroup: !GetAtt SecurityGroupStack.Outputs.DatabaseSecurityGroup
        DBSecretArn: !GetAtt SecretsStack.Outputs.DBSecretArn
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Application Load Balancer
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [VPCStack, SecurityGroupStack]
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/alb-loadbalancer.yaml'
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnets: !GetAtt VPCStack.Outputs.PublicSubnets
        ALBSecurityGroup: !GetAtt SecurityGroupStack.Outputs.ALBSecurityGroup
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ECS Cluster
  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/ecs-cluster.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # IAM Roles
  IAMStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [SecretsStack, ECRStack]
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/iam-roles.yaml'
      Parameters:
        Environment: !Ref Environment
        SecretsArn: !GetAtt SecretsStack.Outputs.AllSecretsArn
        ECRRepositoryArn: !GetAtt ECRStack.Outputs.RepositoryArn
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ECS Service
  ECSServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ECSClusterStack, ALBStack, RDSStack, IAMStack]
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/ecs-service.yaml'
      Parameters:
        Environment: !Ref Environment
        ClusterArn: !GetAtt ECSClusterStack.Outputs.ClusterArn
        TargetGroupArn: !GetAtt ALBStack.Outputs.TargetGroupArn
        PrivateSubnets: !GetAtt VPCStack.Outputs.PrivateSubnets
        ECSSecurityGroup: !GetAtt SecurityGroupStack.Outputs.ECSSecurityGroup
        TaskExecutionRoleArn: !GetAtt IAMStack.Outputs.TaskExecutionRoleArn
        TaskRoleArn: !GetAtt IAMStack.Outputs.TaskRoleArn
        ECRRepositoryUri: !GetAtt ECRStack.Outputs.RepositoryUri
        DBSecretArn: !GetAtt SecretsStack.Outputs.DBSecretArn
        AppSecretsArn: !GetAtt SecretsStack.Outputs.AppSecretsArn
        DBEndpoint: !GetAtt RDSStack.Outputs.DBEndpoint
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # CodePipeline
  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ECSServiceStack, ECRStack, IAMStack]
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplatesBucket}/codepipeline.yaml'
      Parameters:
        Environment: !Ref Environment
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        ECRRepositoryUri: !GetAtt ECRStack.Outputs.RepositoryUri
        ECSClusterName: !GetAtt ECSClusterStack.Outputs.ClusterName
        ECSServiceName: !GetAtt ECSServiceStack.Outputs.ServiceName
        CodeBuildRoleArn: !GetAtt IAMStack.Outputs.CodeBuildRoleArn
        CodePipelineRoleArn: !GetAtt IAMStack.Outputs.CodePipelineRoleArn
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  LoadBalancerDNS:
    Description: Application Load Balancer DNS
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNS
  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRStack.Outputs.RepositoryUri
  PipelineUrl:
    Description: CodePipeline URL
    Value: !GetAtt CodePipelineStack.Outputs.PipelineUrl
  ClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSClusterStack.Outputs.ClusterName
  ServiceName:
    Description: ECS Service Name
    Value: !GetAtt ECSServiceStack.Outputs.ServiceName