AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager for E-Commerce Backend'

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
    Default: ecommerce-backend

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/database'
      Description: RDS PostgreSQL credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "ecommerce_admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/app-secrets'
      Description: Application secrets (Stripe, JWT)
      SecretString: |
        {
          "STRIPE_SECRET_KEY": "sk_test_placeholder_replace_me",
          "STRIPE_PUBLISHABLE_KEY": "pk_test_placeholder_replace_me",
          "JWT_SECRET": "replace_with_256_bit_secret_key_minimum_32_characters_long"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment

  CorsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/cors-config'
      Description: CORS configuration
      SecretString: !Sub |
        {
          "CORS_ALLOWED_ORIGINS": "https://${Environment}.yourdomain.com"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DBSecretArn:
    Value: !Ref DBSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-secret-arn'
  AppSecretsArn:
    Value: !Ref AppSecrets
    Export:
      Name: !Sub '${ProjectName}-${Environment}-app-secrets-arn'
  CorsSecretArn:
    Value: !Ref CorsSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-cors-secret-arn'
  AllSecretsArn:
    Value: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ProjectName}/${Environment}/*'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-all-secrets-arn'